namespace SwiftDrop.ViewModels
{
    /// <summary>
    /// Data transfer object representing a single point on the courier's delivery map.
    /// Markers are generated by <see cref="SwiftDrop.Services.CourierService"/>
    /// and passed to the Leaflet.js map on the courier dashboard.
    /// </summary>
    public class MapMarkerDto
    {
        /// <summary>Primary key of the order this marker belongs to.</summary>
        public int OrderId { get; set; }

        /// <summary>WGS-84 latitude.</summary>
        public decimal Lat { get; set; }

        /// <summary>WGS-84 longitude.</summary>
        public decimal Lng { get; set; }

        /// <summary>Label shown in the map tooltip (e.g. "[Pickup #5] Pizza Palace").</summary>
        public string Title { get; set; } = string.Empty;

        /// <summary>Marker category: <c>"Pickup"</c> for a restaurant, <c>"Delivery"</c> for the customer.</summary>
        public string Type { get; set; } = string.Empty;

        /// <summary>
        /// Suggested stop sequence produced by the route optimization algorithm.
        /// Lower numbers should be visited first.
        /// </summary>
        public int RouteOrder { get; set; }
    }
}
